### ISSUE TITLE
How can I change de styles from the component?

### ISSUE THREAD

**Issue by zehguilherme** [jnprr/blazor-breadcrumb-navigation#8]

**Comment by cschulzsuper** [comment]
I'll try to drop you an example in the coming days.

**Comment by cschulzsuper** [comment]
You have multiple options.

### Option 1

You can add a CSS class to the `BreadcrumbNavigation` component and define a styling in this CSS class. 

``` html
<BreadcrumbNavigation CssClass="test" />
```

``` css
.test li {
    font-weight: bold
}

.test a.active {
    font-style: italic
}

.test li {
    color: red;
    content: "/\0023";
}
```

If you define the style as part of a CSS in a Blazor component, like `MainLayout.razor.css`, you need to add `::deep` to tell the compiler that the style needs to be applied to child components as well.

``` css
::deep .test li {
    font-weight: bold
}

::deep .test a.active {
    font-style: italic
}

::deep .test li {
    color: red;
    content: "/\0023";
}
```

### Option 2

You can apply additional arguments to any breadcrumb and modify the style directly.

``` csharp
public class IndexBreadcrumb : RootBreadcrumb
{
    public override void Configure(BreadcrumbBuilder builder)
        => builder
            .LeftIcon("oi oi-home")
            .Link("Home", string.Empty,
                new KeyValuePair<string, object>("style", "color:red"));
}
```

Of course, you can also just apply a CSS class like this.

Please let me know, if one of the options works for you.
